#!/bin/sh

rm -rf testFolder
mkdir testFolder
cd testFolder

touch fileA
# REDIRECT OUTPUT TO FILE
cal 4 2017 > fileA
cat fileA
# OUTPUT:
#      April 2017
# Su Mo Tu We Th Fr Sa
#                    1
#  2  3  4  5  6  7  8
#  9 10 11 12 13 14 15
# 16 17 18 19 20 21 22
# 23 24 25 26 27 28 29
# 30

ls -l >> fileA
# REDIRECT OUTPUT AS FILE APPEND
echo "hello world" >> fileA
cat fileA
# OUTPUT:
#      April 2017
# Su Mo Tu We Th Fr Sa
#                    1
#  2  3  4  5  6  7  8
#  9 10 11 12 13 14 15
# 16 17 18 19 20 21 22
# 23 24 25 26 27 28 29
# 30
# total 4
# -rw-r--r--    1 root     root           145 Oct 20 08:53 fileA
# hello world
