#!/bin/sh

rm -rf testFolder
mkdir testFolder
cd testFolder

touch fileA
ls -l
# OUTPUT:
# -rw-r--r--    1 root     root             0 Oct 20 07:51 fileA

umask
# OUTPUT: 0022

umask 0000
umask
# OUTPUT: 0000

rm fileA
touch fileA
ls -l
# OUTPUT:
# -rw-rw-rw-    1 root     root             0 Oct 20 07:51 fileA

rm fileA
umask 0266
touch fileA
ls -l
# OUTPUT:
# -r--------    1 root     root             0 Oct 20 07:51 fileA
