#!/bin/sh

rm -rf testFolder
mkdir testFolder
cd testFolder

touch fileA

echo "a bb ccc" >> fileA
wc fileA
# OUTPUT: 1 3 9 fileA

echo "dd ee" >> fileA
wc fileA
# OUTPUT: 2 5 15 fileA

echo "1234567890" >> fileA
wc fileA
# OUTPUT: 3 6 26 fileA

wc -l fileA
# OUTPUT: 3 fileA
wc -w fileA
# OUTPUT: 6 fileA
wc -c fileA
# OUTPUT: 26 fileA
